@extends('layouts.wrapper')
@section('content')

<div class="main-content">

    <div class="cover">
      <div class="hi"></div>
    </div>
  <div class="tv">
        <div class="screen mute" id="tv"></div>
  </div>

  <div class="homepage-content">
      <div name="our-mission" class="our-mission" data-level="primary">
          <div class="row">
              <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                  <h2>Our Mission</h2>
              </div>
              <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                  <strong>
                      Put Simply:
                  </strong>
                  <ul>
                      <li>We believe that confidence is generated by self improvement</li>
                      <li>Self improvement only occurs when recognition of your efforts exist</li>
                      <li>When recognition exists this restarts the motviation loop to be a better person</li>
                  </ul>
              </div>
              <div class="column small-12 medium-8 large-8 text-center large-offset-2 global-spacing bottom">
                  <hr>
              </div>

                <div class="columns small-12 medium-12 large-12">
                    <div name="effort-output-vs-feedback" data-level="secondary">
                        <div class="row">
                            <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                                <h3>Effort Output vs Feedback</h3>
                            </div>
                            <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                                <p>You work yourself to the knuckle but you feel empty at the end of it.</p>
                                <p>We provide you your very own structured self improvement plan that grows as you do</p>
                            </div>
                        </div>
                    </div>
                </div>



              <div class="columns small-12 medium-12 large-12">
                  <div name="self-progression" data-level="secondary">
                      <div class="row">
                          <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                              <h3>Self Progression</h3>
                          </div>
                          <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                              <p>Mission Complete encourages a stronger, faster, smarter, wealthier and above all - happier you</p>
                          </div>
                        </div>
                  </div>
              </div>

              <div class="columns small-12 medium-12 large-12">
                  <div name="acheive-and-quantify" data-level="secondary">
                      <div class="row">
                          <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                              <h3>Acheive and Quantify</h3>
                          </div>
                          <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                              <p>All that effort deserves a reward, Mission Complete shows you how far you've come</p>
                          </div>
                        </div>
                  </div>
              </div>

              <div class="columns small-12 medium-12 large-12">
                  <div name="completion-and-self-maintenance" data-level="secondary">
                      <div class="row">
                          <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                              <h3>Completion and Self Maintenance</h3>
                          </div>
                          <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                              <p>Once you've made some progression you have to maintain it <br />
                              Mission Complete takes care of reminding you when and how to do that.</p>
                          </div>
                        </div>
                  </div>
              </div>


          </div>
      </div>
      <div class="parallax-window" data-parallax="scroll" data-image-src="{{{ asset('images/old-planes.jpg') }}}"></div>
      <!--<div name="your-mission" class="your-mission" data-level="primary">
          <div class="row">
              <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing top bottom">
                  <h2>Your Mission</h2>
              </div>

              <div class="columns small-12 medium-12 large-12">
                  <div name="test" data-level="secondary">
                      <div class="row">
                          <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                              <h3>Test test</h3>
                          </div>
                          <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                              <p>Have your very own structured self improvement plan that grows as you do</p>
                          </div>
                        </div>
                  </div>
              </div>

              <div class="columns small-12 medium-12 large-12">
                  <div name="test-1" data-level="secondary">
                      <div class="row">
                          <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                              <h3>Test 1 </h3>
                          </div>
                          <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                              <p>Have your very own structured self improvement plan that grows as you do</p>
                          </div>
                        </div>
                  </div>
              </div>

              <div class="columns small-12 medium-12 large-12">
                  <div name="test-2" data-level="secondary">
                      <div class="row">
                          <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                              <h3>Test 2</h3>
                          </div>
                          <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                              <p>Have your very own structured self improvement plan that grows as you do</p>
                          </div>
                        </div>
                  </div>
              </div>

              <div class="columns small-12 medium-12 large-12">
                  <div name="test-3" data-level="secondary">
                      <div class="row">
                          <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                              <h3>Test 3</h3>
                          </div>
                          <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                              <p>Have your very own structured self improvement plan that grows as you do</p>
                          </div>
                        </div>
                  </div>
              </div>

              <div class="columns small-12 medium-12 large-12">
                  <div name="test-4" data-level="secondary">
                      <div class="row">
                          <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                              <h3>Test 4</h3>
                          </div>
                          <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                              <p>Have your very own structured self improvement plan that grows as you do</p>
                          </div>
                      </div>
                  </div>
              </div>

            <div class="columns small-12 medium-12 large-12">
                <div name="test-4" data-level="secondary">
                    <div class="row">
                        <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                            <h3>Test 4</h3>
                        </div>
                        <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                            <p>Have your very own structured self improvement plan that grows as you do</p>
                        </div>
                    </div>
                </div>
            </div>

              <div class="columns small-12 medium-12 large-12">
                  <div name="test-4" data-level="secondary">
                      <div class="row">
                          <div class="column small-12 medium-4 large-4 text-center large-offset-4 global-spacing bottom">
                              <h3>Test 4</h3>
                          </div>
                          <div class="column small-12 medium-8 large-8 text-center large-offset-2">
                              <p>Have your very own structured self improvement plan that grows as you do</p>
                          </div>
                      </div>
                  </div>
              </div>

          </div>
      </div>-->


      <footer>
          <div class="row">
              <div class="small-12 medium-6 large-6 column">
                  <strong>Mission Complete ©</strong>
              </div>
              <div class="small-12 medium-6 large-6 column">
                  <a href="mailto:ellis.taylor499@gmail.com">Contact Us</a>
              </div>
          </div>
      </footer>
    </div>

</div>


@endsection
